### ISSUE TITLE
hide and show method with inappbrowser didn't work in phonegap application

### ISSUE THREAD

**Issue by Belheni** [gandhirajan/Cordova_InAppBrowser#1]
@gandhirajan i need your help Mr, I'am developing a phonegap application which is based on webview concept and i want to show and hide the window according to some uses of the client.. hide() and show() method didn't work on ios and android devices despite the documentation of inappbrowser plugin is very clear and simple.. this is an example of code:

win = cordova.InAppBrowser.open("https://www.facebook.com/", "_blank","location=no,EnableViewPortScale=yes,toolbar=no" );
    setTimeout(function(){ alert("hide the window"); win.hide(); }, 10000);
        setTimeout(function(){ alert("show the window"); win.show(); }, 20000); 

Have you any idea about that please?

**Comment by gandhirajan** [comment]
If you have the proper window reference, it should work fine. I doubt the window reference you are holding. Any error on device console?

**Comment by Belheni** [comment]
the error is that win.hide is not a function! i don't understand why this error is triggered.. i send you the code and in the documentation defined clearly the method hide().. Also when i inspert the object win created by inappbrowser, it shows me: (there isn't the hide() method)
![errorinappbrowser](https://user-images.githubusercontent.com/9254359/32172309-6f315556-bd7b-11e7-952e-33e5e1dfbf2a.PNG)

**Comment by gandhirajan** [comment]
I don't see any of the window object attributes in your debug screenshot. I guess you are not getting the right window handle

**Comment by Belheni** [comment]
And how to obtain the right window handle? All other methods of the window object work fine and i send you the simple code that i use to test with it.. did you have an example of working hide method? i want to know the difference..Thanks @gandhirajan..

**Comment by gandhirajan** [comment]
I m really not sure. Need to check it on some device. But as per the documentation it should work seamlessly. But what you are getting is definitely not the window object i believe

**Comment by Belheni** [comment]
But like you see in the image, it's an inappbrowser object with all defined methods.. Please check it on some device because i really need this method in my application.

**Comment by gandhirajan** [comment]
Sorry I cant commit on this now. But will have a look if I find sometime tomorrow

**Comment by Belheni** [comment]
Yes @gandhirajan  as you like and sorry again for the disturbance

**Comment by gandhirajan** [comment]
hey i tested this code by creating a new project in cordova 7 and by adding browser platform and it works. I Just test close by adding "setTimeout(function(){ ref.close(); }, 7000);" code in my sample app's inapp click function. So it should work fine according to me. Please check all your app configs again.
